image: sikalabs/ci

variables:
  TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID
  IMAGE: $CI_REGISTRY_IMAGE:$TAG

stages:
  - build
  - deploy

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.19.2-debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context ./src
      --dockerfile ./src/Dockerfile
      --destination $IMAGE

deploy dev:
  stage: deploy
  script:
    - |
      slu gitlab update-file \
        --gitlab-url https://gitlab.sikalabs.com \
        --token $ARGOCD_COMMITTER_TOKEN \
        --project-id $ARGOCD_APPS_PROJECT_ID \
        --branch $ARGOCD_APPS_BRANCH \
        --file $IMAGE_VALUES_FILE_DEV \
        --content "image: $IMAGE" \
        --committer-email "integritty-bot@gitlab.sikalabs.io" \
        --committer-name "[bot] integritty-bot" \
        --commit-message "[auto] feat(example): Update image using CI ($TAG)"

